version: '3.0'
services:
    mongodb:
      image: mongo
      container_name: mongodb
      environment:
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      volumes:
        - ./db:/data/db
        - ./mongo-entrypoint:/docker-entrypoint-initdb.d:ro 
      ports:
        - 27017:27017
      restart: unless-stopped

